#!/usr/bin/env python3
"""Open-loop replay of a rollout CSV on real DEXTRA hardware.

Reads ``target_*`` columns from a CSV generated by ``rollout_log.py`` and
sends the position targets to the 12 Dynamixel AX-18A servos at the
recorded control frequency.

Usage::

    python replay_csv.py --csv logs/rollout/rollout.csv

    # Dry-run (no servo writes)
    python replay_csv.py --csv logs/rollout/rollout.csv --dry-run
"""

import argparse
import csv
import signal
import sys
import time

import numpy as np
import yaml

from hardware.dynamixel_interface import DynamixelInterface
from utils.timing import RateController

NUM_JOINTS = 12


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_config(path: str) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def build_hardware(cfg: dict) -> DynamixelInterface:
    joints = cfg["joints"]
    return DynamixelInterface(
        port=cfg["dynamixel"]["port"],
        baudrate=cfg["dynamixel"]["baudrate"],
        servo_ids=[j["servo_id"] for j in joints],
        offsets_raw=[j["offset_raw"] for j in joints],
        lower_rads=[j["lower_rad"] for j in joints],
        upper_rads=[j["upper_rad"] for j in joints],
    )


def load_targets_from_csv(csv_path: str) -> tuple["np.ndarray", list]:
    """Parse target_0..11 columns from rollout CSV.

    Returns:
        targets : (N, 12) float32 array of position targets [rad]
        joint_names : list of 12 joint names from CSV metadata comment
    """
    targets = []
    joint_names = []

    with open(csv_path, newline="") as f:
        reader = csv.reader(f)

        # First row: metadata comment
        meta_row = next(reader)
        meta_str = ",".join(meta_row)
        if "joint_names=" in meta_str:
            jn_part = meta_str.split("joint_names=")[-1].strip()
            joint_names = [n.strip() for n in jn_part.split(",") if n.strip()]

        # Second row: header
        header = next(reader)
        target_cols = [i for i, h in enumerate(header) if h.startswith("target_")]
        if len(target_cols) != NUM_JOINTS:
            raise ValueError(
                f"Expected {NUM_JOINTS} target_* columns, found {len(target_cols)}. "
                f"Header: {header}"
            )

        for row in reader:
            targets.append([float(row[c]) for c in target_cols])

    return np.array(targets, dtype=np.float32), joint_names


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Open-loop CSV replay on DEXTRA hardware.")
    parser.add_argument("--csv", type=str, required=True,
                        help="Path to rollout CSV from rollout_log.py")
    parser.add_argument("--config", type=str, default="config.yaml",
                        help="Path to config.yaml (default: config.yaml)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Parse and time the replay without writing to servos")
    args = parser.parse_args()

    # --- Load config ---
    cfg = load_config(args.config)
    freq        = cfg["control"]["frequency_hz"]
    joint_lower = np.array([j["lower_rad"] for j in cfg["joints"]], dtype=np.float32)
    joint_upper = np.array([j["upper_rad"] for j in cfg["joints"]], dtype=np.float32)

    # --- Load CSV ---
    print(f"[replay] Loading CSV: {args.csv}")
    all_targets, joint_names = load_targets_from_csv(args.csv)
    total_frames = all_targets.shape[0]

    print(f"[replay] Frames: {total_frames}  ({total_frames / freq:.1f}s @ {freq}Hz)")
    if joint_names:
        print(f"[replay] Joint order: {joint_names}")
    if args.dry_run:
        print("[replay] DRY-RUN — no servo commands will be sent")

    # --- Initialize hardware ---
    dxl = None
    if not args.dry_run:
        dxl = build_hardware(cfg)
        dxl.connect()

    # --- Signal handler ---
    running = True

    def sigint_handler(sig, frame):
        nonlocal running
        print("\n[replay] Interrupt received, shutting down...")
        running = False

    signal.signal(signal.SIGINT, sigint_handler)

    # --- Replay loop ---
    print(f"[replay] Starting open-loop replay ({total_frames} steps @ {freq}Hz)...")
    rate = RateController(freq)
    rate.reset()
    t_start = time.monotonic()

    for step in range(total_frames):
        if not running:
            break

        target = np.clip(all_targets[step], joint_lower, joint_upper)

        if dxl:
            dxl.write_position_targets(target)

        if (step + 1) % 100 == 0 or step == total_frames - 1:
            elapsed = time.monotonic() - t_start
            print(f"[replay] step {step+1:4d}/{total_frames}  elapsed={elapsed:.1f}s")

        rate.sleep()

    elapsed_total = time.monotonic() - t_start
    print(f"[replay] Finished {step + 1} steps in {elapsed_total:.1f}s")

    # --- Shutdown ---
    if dxl:
        dxl.go_to_home()
        time.sleep(1.0)
        dxl.disconnect()

    print("[replay] Done.")


if __name__ == "__main__":
    main()
